/**
 * The generator contract.
 *
 * A generator is a pure function from an index to a question. Given the same
 * index it produces the same question forever, which is what makes the bank
 * reproducible: the seed script can be re-run, the import is keyed on a stable
 * `sourceKey`, and re-running it updates rows rather than duplicating them.
 *
 * Two rules hold everywhere and are worth stating before any of the maths:
 *
 *  1. THE ANSWER IS COMPUTED, NEVER TYPED. A generator picks parameters and
 *     then works the question out. `solve 3x + 7 = 22` is built by choosing
 *     x = 5, a = 3, b = 7 and computing c = 22 — so the answer cannot be wrong
 *     unless the arithmetic in this file is wrong, and that is tested.
 *  2. DISTRACTORS ARE REAL MISTAKES. A wrong option is generated by making a
 *     specific error a student actually makes — sign slip, forgetting to halve,
 *     dividing instead of multiplying — not by jittering the right answer.
 *     Random distractors are eliminable by inspection, which turns a maths
 *     question into a spot-the-odd-one-out question.
 *
 * `check` is the third rule, and the reason this can be trusted at 2,000
 * questions: a generator may supply an independent verification of its own
 * answer — substitute the root back into the equation, differentiate and
 * confirm the stationary point, re-derive the hypotenuse. The test harness runs
 * `check` over every variant of every generator, so a broken generator fails a
 * test rather than reaching a student.
 */

import {
  bandFor,
  isKnownSubtopic,
  type CurriculumLevel,
  type BankQuestionType,
  type Subject,
} from "../taxonomy";

/* ==========================================================================
   Seeded randomness
   ========================================================================== */

/**
 * Mulberry32, the same generator the Arena deals hands with.
 *
 * Deterministic and cheap. Not cryptographic, and nothing here needs it to be —
 * the worst outcome of a predictable sequence is that a student who reads the
 * source knows which parameters question 7 uses, and the source is theirs.
 */
export class Rng {
  private state: number;

  constructor(seed: number) {
    this.state = seed >>> 0;
  }

  /** [0, 1) */
  next(): number {
    this.state = (this.state + 0x6d2b79f5) >>> 0;
    let t = this.state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  }

  /** Integer in [min, max], inclusive both ends. */
  int(min: number, max: number): number {
    if (max < min) throw new Error(`Rng.int with empty range ${min}..${max}`);
    return min + Math.floor(this.next() * (max - min + 1));
  }

  /** Integer in [min, max] excluding zero — the usual need for a coefficient. */
  nonZero(min: number, max: number): number {
    if (min > 0 || max < 0) return this.int(min, max);
    for (let attempt = 0; attempt < 50; attempt++) {
      const value = this.int(min, max);
      if (value !== 0) return value;
    }
    return min < 0 ? -1 : 1;
  }

  /** ±1. */
  sign(): number {
    return this.next() < 0.5 ? -1 : 1;
  }

  bool(probability = 0.5): boolean {
    return this.next() < probability;
  }

  pick<T>(items: readonly T[]): T {
    if (items.length === 0) throw new Error("Rng.pick from an empty list");
    return items[Math.floor(this.next() * items.length)];
  }

  /** A new list, shuffled. */
  shuffle<T>(items: readonly T[]): T[] {
    const out = [...items];
    for (let i = out.length - 1; i > 0; i--) {
      const j = Math.floor(this.next() * (i + 1));
      [out[i], out[j]] = [out[j], out[i]];
    }
    return out;
  }

  /** `count` distinct integers from [min, max]. */
  distinct(count: number, min: number, max: number): number[] {
    const span = max - min + 1;
    if (count > span) throw new Error(`Cannot take ${count} distinct values from ${span}`);
    const seen = new Set<number>();
    while (seen.size < count) seen.add(this.int(min, max));
    return [...seen];
  }
}

/** A stable 32-bit seed from a string, so a generator key always deals the same. */
export function seedFromKey(key: string): number {
  let h = 2166136261;
  for (let i = 0; i < key.length; i++) {
    h ^= key.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

/* ==========================================================================
   What a generator produces
   ========================================================================== */

export interface GeneratedOption {
  text: string;
  isCorrect: boolean;
}

export interface GeneratedQuestion {
  /** Stable across runs. `${generatorKey}:${index}` unless a generator says otherwise. */
  sourceKey: string;
  subject: Subject;
  topic: string;
  subtopic: string;
  curriculumLevel: CurriculumLevel;
  /** 1–10, within-level. The band is derived, never stored separately. */
  difficulty: number;
  questionType: BankQuestionType;
  prompt: string;
  /** Authoring order. Serving shuffles it, exactly as the Arena does. */
  options: GeneratedOption[];
  /** The canonical answer as text. For MCQ this equals the correct option. */
  answer: string;
  explanation: string;
  estimatedSeconds: number;
  marks: number;
  /**
   * True when this question genuinely needs a calculator.
   *
   * Battles serve only questions where it is false. A two-minute race in which
   * one player has a calculator open and the other does not is not a test of
   * anything, and "type 3.7 x 6.2 faster" is not the skill being measured — so
   * the bank keeps these for practice and revision, where the timer is not the
   * point, and the Arena never deals them.
   */
  calculator: boolean;
  sourceName: string | null;
  sourceUrl: string | null;
  sourceLicence: string | null;
}

/** What a generator body returns; the framework fills in the rest. */
export interface QuestionDraft {
  prompt: string;
  answer: string;
  explanation: string;
  /** Wrong answers, each one a mistake a student actually makes. */
  distractors?: string[];
  /** Overrides the generator's default when one variant is harder than its siblings. */
  difficulty?: number;
  marks?: number;
  estimatedSeconds?: number;
  questionType?: BankQuestionType;
  /** Overrides the generator's default for one variant. */
  calculator?: boolean;
  /**
   * An independent check of this question's own answer, run by the tests over
   * every variant. Return a message to fail, or null to pass. Optional, because
   * some answers have no cheaper verification than the derivation itself — but
   * anything that can be substituted back in should be.
   */
  check?: () => string | null;
}

export interface GeneratorSpec {
  /** Stable id. Appears in every `sourceKey` it produces, so never rename casually. */
  key: string;
  topic: string;
  subtopic: string;
  curriculumLevel: CurriculumLevel;
  difficulty: number;
  /** How many questions to deal from this generator. */
  variants: number;
  questionType?: BankQuestionType;
  marks?: number;
  estimatedSeconds?: number;
  subject?: Subject;
  /**
   * Does this generator need a calculator? Defaults to false, so a new
   * generator has to opt IN to being excluded from battles — the wrong default
   * would quietly shrink the Arena pool as the bank grew.
   */
  calculator?: boolean;
  build: (rng: Rng, index: number) => QuestionDraft;
}

export interface Generator extends GeneratorSpec {
  subject: Subject;
  /** Deal variant `index`. Deterministic. */
  at(index: number): GeneratedQuestion;
  /** Deal every variant. */
  all(): GeneratedQuestion[];
}

/**
 * Default effort per question, before a generator overrides it.
 *
 * Derived from difficulty rather than set per question, so the numbers stay
 * consistent across two thousand questions written over many files. Roughly:
 * an easy recall question is a few seconds, an expert multi-step problem is a
 * couple of minutes.
 */
export function defaultSeconds(difficulty: number): number {
  return Math.round(20 + difficulty * 11);
}

export function defaultMarks(difficulty: number): number {
  if (difficulty <= 2) return 1;
  if (difficulty <= 5) return 2;
  if (difficulty <= 7) return 3;
  if (difficulty <= 9) return 4;
  return 5;
}

/**
 * Turn a spec into a generator.
 *
 * The validation here is deliberately loud. A generator that produces a
 * duplicate option, an empty explanation or an unknown subtopic is a bug that
 * would otherwise sit in the bank looking like data, so it throws at build time
 * where the seed script and the tests both see it.
 */
export function generator(spec: GeneratorSpec): Generator {
  const subject = spec.subject ?? "maths";

  if (!isKnownSubtopic(spec.topic, spec.subtopic)) {
    throw new Error(`Generator ${spec.key}: unknown subtopic ${spec.topic}/${spec.subtopic}`);
  }
  if (spec.variants < 1) {
    throw new Error(`Generator ${spec.key}: needs at least one variant`);
  }

  const build = (index: number, salt: number): GeneratedQuestion => {
    /* Seeded from the key AND the index, so adding a variant to one generator
       does not reshuffle the parameters of every other question it makes. */
    const rng = new Rng(seedFromKey(salt === 0 ? `${spec.key}#${index}` : `${spec.key}#${index}@${salt}`));
    const draft = spec.build(rng, index);

    const difficulty = draft.difficulty ?? spec.difficulty;
    const questionType = draft.questionType ?? spec.questionType ?? "MCQ_SINGLE";

    return {
      sourceKey: `${spec.key}:${index}`,
      subject,
      topic: spec.topic,
      subtopic: spec.subtopic,
      curriculumLevel: spec.curriculumLevel,
      difficulty,
      questionType,
      prompt: draft.prompt.trim(),
      options: buildOptions(spec.key, index, questionType, draft, rng),
      answer: draft.answer.trim(),
      explanation: draft.explanation.trim(),
      estimatedSeconds: draft.estimatedSeconds ?? spec.estimatedSeconds ?? defaultSeconds(difficulty),
      marks: draft.marks ?? spec.marks ?? defaultMarks(difficulty),
      calculator: draft.calculator ?? spec.calculator ?? false,
      sourceName: null,
      sourceUrl: null,
      sourceLicence: null,
    };
  };

  /**
   * The whole run, deduplicated.
   *
   * Random parameters collide — with twenty variants drawn from a few hundred
   * combinations, a repeat is not unlikely, it is expected. Dealing them
   * independently produced a bank where the same question appeared twice under
   * two ids, which is precisely the defect the Arena pool had to work around.
   * So a variant whose prompt has already appeared is re-rolled with a salted
   * seed until it is new.
   *
   * When a generator genuinely cannot produce as many distinct questions as it
   * claims — a polygon-angles generator has only so many polygons — this
   * throws rather than quietly returning fewer. That is a real limit on the
   * bank's size and it should be stated in the generator's `variants`, not
   * discovered later by a student meeting the same question twice.
   */
  const MAX_RESALTS = 60;
  let cached: GeneratedQuestion[] | null = null;

  const all = (): GeneratedQuestion[] => {
    if (cached) return cached;

    const seen = new Set<string>();
    const out: GeneratedQuestion[] = [];

    for (let index = 0; index < spec.variants; index++) {
      let question: GeneratedQuestion | null = null;

      for (let salt = 0; salt <= MAX_RESALTS; salt++) {
        const candidate = build(index, salt);
        const fingerprint = candidate.prompt.trim().toLowerCase().replace(/\s+/g, " ");
        if (seen.has(fingerprint)) continue;
        seen.add(fingerprint);
        question = candidate;
        break;
      }

      if (!question) {
        throw new Error(
          `Generator ${spec.key}: cannot produce ${spec.variants} distinct questions ` +
            `(gave up at variant ${index} after ${MAX_RESALTS} attempts). ` +
            `Lower its \`variants\`, or widen the parameters it draws from.`,
        );
      }

      out.push(question);
    }

    cached = out;
    return out;
  };

  return {
    ...spec,
    subject,
    at: (index: number) => {
      if (index < 0 || index >= spec.variants) {
        throw new Error(`Generator ${spec.key}: variant ${index} out of range`);
      }
      return all()[index];
    },
    all,
  };
}

/** Every choice question has exactly this many options: the answer plus three. */
export const OPTIONS_PER_QUESTION = 4;
const DISTRACTORS_PER_QUESTION = OPTIONS_PER_QUESTION - 1;

/**
 * Assemble and sanity-check the option list.
 *
 * Every choice question ends up with exactly four options — the answer and
 * three wrong ones. A four-option question is the shape students expect and the
 * shape the battle UI is built for; a three-option question that slipped
 * through raised the odds of a lucky guess from one-in-four to one-in-three on
 * that question alone.
 *
 * Distractors are deduplicated against each other AND against the answer, which
 * matters more than it sounds: a generator whose "forgot to halve" mistake
 * happens to coincide with the right answer for one variant would otherwise
 * produce a question with two correct options, and nothing downstream would
 * notice.
 *
 * A generator is still expected to author its own distractors — real mistakes,
 * not noise. `topUpNumericDistractors` only runs when dedup has left a numeric
 * question short of three, and it fills the gap with the errors a numeric
 * answer actually invites: an order-of-magnitude slip, a dropped factor of two,
 * a sign error. A non-numeric question that comes up short is a generator bug
 * and throws, because there is no safe way to invent a fourth word.
 */
function buildOptions(
  key: string,
  index: number,
  questionType: BankQuestionType,
  draft: QuestionDraft,
  rng: Rng,
): GeneratedOption[] {
  if (questionType === "NUMERIC" || questionType === "SHORT_ANSWER") return [];

  const answer = draft.answer.trim();
  const seen = new Set([normalise(answer)]);
  const distractors: string[] = [];

  const consider = (raw: string): void => {
    const text = raw.trim();
    const norm = normalise(text);
    if (text === "" || seen.has(norm) || distractors.length >= DISTRACTORS_PER_QUESTION) return;
    seen.add(norm);
    distractors.push(text);
  };

  for (const raw of draft.distractors ?? []) consider(raw);

  if (distractors.length < DISTRACTORS_PER_QUESTION) {
    for (const candidate of topUpNumericDistractors(answer, DISTRACTORS_PER_QUESTION)) {
      consider(candidate);
    }
  }

  if (distractors.length < DISTRACTORS_PER_QUESTION) {
    throw new Error(
      `Generator ${key} variant ${index}: only ${distractors.length} usable distractor(s) after ` +
        `de-duplication. Every choice question needs ${OPTIONS_PER_QUESTION} options — author ` +
        `${DISTRACTORS_PER_QUESTION} distinct wrong answers, each a mistake a student actually makes.`,
    );
  }

  return rng.shuffle([
    { text: answer, isCorrect: true },
    ...distractors.slice(0, DISTRACTORS_PER_QUESTION).map((text) => ({ text, isCorrect: false })),
  ]);
}

/**
 * Last-resort distractors for a numeric answer.
 *
 * Only reached when a generator's own distractors collapsed on dedup and the
 * question would otherwise have three options. The transformations are the
 * classic numeric slips — times ten, times two, halve, negate, ±10% — applied
 * to the number embedded in the answer while its prefix and units are kept, so
 * "6.4 × 10⁻³ mol" yields "1.28 × 10⁻² mol" rather than a bare number. Anything
 * that does not contain a number returns nothing and the caller throws.
 */
export function topUpNumericDistractors(answer: string, wanted: number): string[] {
  const match = answer.match(/^(.*?)(-?\d[\d,]*(?:\.\d+)?)(.*)$/s);
  if (!match) return [];

  const [, prefix, rawNumber, suffix] = match;
  const value = Number(rawNumber.replace(/,/g, ""));
  if (!Number.isFinite(value)) return [];

  const grouped = rawNumber.includes(",");
  const decimals = rawNumber.includes(".") ? rawNumber.split(".")[1].length : 0;

  const format = (n: number): string | null => {
    if (!Number.isFinite(n)) return null;
    const places = Number.isInteger(n) ? decimals : Math.max(decimals, Math.min(4, countDecimals(n)));
    let body = n.toFixed(places);
    if (places > decimals) body = body.replace(/\.?0+$/, "");
    if (grouped) {
      const [whole, frac] = body.split(".");
      body = Number(whole).toLocaleString("en-US") + (frac ? `.${frac}` : "");
    }
    return `${prefix}${body}${suffix}`;
  };

  const seedTransforms = value !== 0
    ? [value * 10, value * 2, value / 2, -value, value / 10, value * 1.1, value * 0.9]
    : [];
  const additive = [value + 1, value - 1, value + 2, value + 10, value - 10];

  const out: string[] = [];
  const seen = new Set([normalise(answer)]);
  for (const candidate of [...seedTransforms, ...additive]) {
    const text = format(candidate);
    if (!text) continue;
    const norm = normalise(text);
    if (seen.has(norm)) continue;
    seen.add(norm);
    out.push(text);
    if (out.length >= wanted) break;
  }
  return out;
}

function countDecimals(n: number): number {
  const s = String(n);
  const dot = s.indexOf(".");
  return dot === -1 ? 0 : s.length - dot - 1;
}

/** Whitespace and case are not meaningful differences between two options. */
function normalise(text: string): string {
  return text.trim().toLowerCase().replace(/\s+/g, " ");
}

/* ==========================================================================
   Distractor helpers
   ========================================================================== */

/**
 * Distractors for a numeric answer, built from named mistakes.
 *
 * Takes candidates in preference order and returns the first few that are
 * distinct from the answer and from each other. Generators pass the specific
 * errors their question invites; this only handles the bookkeeping.
 */
export function pickDistractors(
  answer: string,
  candidates: readonly (string | number | null | undefined)[],
  wanted = 3,
): string[] {
  const seen = new Set([normalise(answer)]);
  const out: string[] = [];

  for (const candidate of candidates) {
    if (candidate === null || candidate === undefined) continue;
    const text = String(candidate).trim();
    if (text === "" || text === "NaN" || text === "Infinity" || text === "-Infinity") continue;
    const norm = normalise(text);
    if (seen.has(norm)) continue;
    seen.add(norm);
    out.push(text);
    if (out.length === wanted) break;
  }

  return out;
}

/**
 * A last-resort spread around a numeric answer.
 *
 * Only for questions where no interesting mistake exists — counting problems,
 * say. Used sparingly and never as the whole distractor set, because "the right
 * answer plus or minus one" is a pattern a student learns to exploit faster
 * than they learn the maths.
 */
export function nearMisses(value: number, offsets: readonly number[] = [1, -1, 2]): string[] {
  return offsets.map((offset) => String(value + offset));
}
